// Commit message validation logic
// Extracted into a separate module so it can be unit tested

const CONVENTIONAL_COMMIT_RE = /^(upd|feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,80}/;

// Auto-generated messages that bypass conventional commit check
const ALLOWED_PREFIXES = ["Rotating Domains Checker:"];

const CYRILLIC_RE = /[\u0400-\u04FF]/;

export interface ValidationResult {
  valid: boolean;
  error?: string;
}

/**
 * Validate a commit message against project rules:
 * 1. Must follow Conventional Commits OR be an allowed auto-generated prefix
 * 2. Must not contain Cyrillic characters (English only)
 */
export function validateCommitMessage(message: string): ValidationResult {
  if (!message || message.trim().length === 0) {
    return { valid: false, error: "Commit message must not be empty" };
  }

  const firstLine = message.split("\n")[0].trim();

  // Check for allowed auto-generated prefixes
  const isAutoGenerated = ALLOWED_PREFIXES.some((prefix) => firstLine.startsWith(prefix));

  // Must match conventional commits OR be an auto-generated message
  if (!isAutoGenerated && !CONVENTIONAL_COMMIT_RE.test(firstLine)) {
    return {
      valid: false,
      error:
        "Commit message must follow Conventional Commits format " +
        "(e.g. feat: add feature, fix: resolve bug, chore: update deps) " +
        "or start with an allowed prefix (e.g. Rotating Domains Checker:)",
    };
  }

  // Check for Cyrillic characters in the entire message
  if (CYRILLIC_RE.test(message)) {
    return {
      valid: false,
      error: "Commit message must be in English (Cyrillic characters detected)",
    };
  }

  return { valid: true };
}
